"""empty message

Revision ID: 692ee9902b23
Revises: 857132501e08
Create Date: 2022-08-24 15:47:34.044021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692ee9902b23'
down_revision = '857132501e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
