"""empty message

Revision ID: bb0e44f16370
Revises: 6c3fac7abf27
Create Date: 2022-08-25 21:04:08.687291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0e44f16370'
down_revision = '6c3fac7abf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
