"""empty message

Revision ID: bc54c7c36b5e
Revises: 0268b5934e17
Create Date: 2022-08-28 01:37:59.355934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc54c7c36b5e'
down_revision = '0268b5934e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('nextval(\'"Show_venue_id_seq"\'::regclass)'))
    op.alter_column('Show', 'artist_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_name'], ['name'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_name'], ['name'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_image_link'], ['image_link'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.alter_column('Show', 'artist_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('nextval(\'"Show_venue_id_seq"\'::regclass)'))
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
