"""empty message

Revision ID: e8bc41c0865b
Revises: bf106d146f9f
Create Date: 2022-08-29 18:35:54.850647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bc41c0865b'
down_revision = 'bf106d146f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('names', sa.String(), nullable=False))
    op.add_column('Artist', sa.Column('image_links', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'name')
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_name'], ['name'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_image_link'], ['image_links'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_name'], ['names'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.alter_column('Show', 'artist_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Show', 'id')
    op.add_column('Artist', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'image_links')
    op.drop_column('Artist', 'names')
    # ### end Alembic commands ###
